# Generated by Django 4.2.1 on 2023-05-12 00:53

import bmsAPP.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=200, validators=[bmsAPP.models.validate_domain])),
                ('expiry_date', models.DateField()),
                ('organization_size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('veri', 'Verified'), ('unveri', 'unverified')], default='unveri', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('no_of_user', models.PositiveIntegerField()),
                ('module', models.CharField(choices=[('P', 'Payroll'), ('L', 'Leave'), ('A', 'Appraisal'), ('At', 'Attendance')], max_length=200)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pd', 'paid'), ('du', 'due')], default='du', max_length=200)),
                ('model_interval', models.CharField(choices=[('1', 'One Month'), ('3', 'Three Month'), ('6', 'Six Month'), ('12', 'One Year')], default='1', max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bmsAPP.client')),
                ('subscription_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bmsAPP.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ram_usage', models.FloatField(max_length=200, validators=[django.core.validators.MinValueValidator(0)])),
                ('hard_disk_usage', models.FloatField(max_length=200, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_users', models.PositiveIntegerField()),
                ('number_of_organizations', models.PositiveIntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bmsAPP.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
